### ISSUE TITLE
Trees just don't have materials

### ISSUE THREAD

**Issue by Fr0dech** [TailsXPrower/sbox-issues#1]
![image](https://user-images.githubusercontent.com/85352886/186487085-e42b99f1-4ca1-4314-b32e-c7a68e716947.png)

**Comment by TailsXPrower** [comment]
Yea, there is such problem, but I think it's Asset.Party problem, because all assets are uploaded to asset.party, but somehow textures are missing.

**Comment by TailsXPrower** [comment]
Fixed
